### ISSUE TITLE
Hangs after a2drive load

### ISSUE THREAD

**Issue by omigeot** [tjboldt/Apple2-IO-RPi#132]
### What happened?

(it might be version 0029 instead of 0028, I did git pull very recently)

Trying to load an hdv file on drive 2, as per the a2drive command example. The command never returns nor gives control back in any way. Tried on big .hdv files from the internet, but it works the same on an empty image created with ProDOS Utilities right on the Pi.

### Hardware Version

Sixth Prototype (Purchased from Terence)

### Firmware Version

000F

### Driver Version

0028 (add live drive loading and regeneration)

### Shell Version

000D (added version info)

### Where are you seeing this problem?

RPI Command

### What computer is this running on?

Apple IIgs

**Comment by tjboldt** [comment]
Apparently I never finished that portion of the code. I will fix that on the weekend. Thanks for bringing it to my attention.
