### ISSUE TITLE
Apple 2 IO RPi show monitor prompt after loading ProDOS 2.4.2 

### ISSUE THREAD

**Issue by wyatt-wong** [tjboldt/Apple2-IO-RPi#73]
After I removed the Apple 5.25 Disk Controller Card from Slot 6 and installed Apple 2 IO RPi to slot 6, I booted up Platinum IIe and found monitor prompt showed on screen after loading ProDOS 2.4.2. Every time I boot up Apple 2 IO RPi, I got a slightly different screen.

![IMG_8435](https://user-images.githubusercontent.com/10095648/152634987-344538b2-ac6d-4390-bbb4-1df2ac9f501c.jpg)

![IMG_8437](https://user-images.githubusercontent.com/10095648/152634996-528ddfb6-43c2-4266-8b23-1287d16a1897.jpg)

![IMG_8438](https://user-images.githubusercontent.com/10095648/152635000-257b4309-84d9-4a79-bbde-9a78d5ca6c5f.jpg)

![IMG_8439](https://user-images.githubusercontent.com/10095648/152635004-26ea0bfe-3193-404d-914c-6cc3c506f4ff.jpg)

On one occasion, the ProDOS 2.4.2 screen was shown forever

![IMG_8436](https://user-images.githubusercontent.com/10095648/152635085-399f0d4f-6812-49c8-a79f-64ac192ab321.jpg)

Due the the Apple 2 IO RPi is very close to the Apple II VGA Scaler, I added a paper in between to avoid short circuit.

**Comment by tjboldt** [comment]
Aside from current draw from other cards, the only other thing I can think of that might cause that is bad solder joints. It's a hand assembled prototype and shipped across the world. Try it with no other cards in the system and if it's still failing, I can send you a refund or a replacement.

**Comment by wyatt-wong** [comment]
This case happened most probably due to the Apple 3.5 Disk Controller Card was installed in Slot 5, even when there are no Apple 3.5 Disk Drive was attached. I would suggest to close to issue. Please refer to Issue 14 for other findings.

**Comment by tjboldt** [comment]
Thanks for the update. Closing issue.
