### ISSUE TITLE
RPI.COMMAND hard coded for slot 7

### ISSUE THREAD

**Issue by tjboldt** [tjboldt/Apple2-IO-RPi#74]
### What happened?

Executing RPI.COMMAND when the card is in a slot other than slot 7 will fail. It's hard coded to slot 7. It should be made to work in other slots like SHELL has been updated to do.

### Hardware Version

Fifth Prototype (Self-assembled)

### Where are you seeing this problem?

RPI Command

### What computer is this running on?

Apple //e (enhanced / platinum)

**Comment by wyatt-wong** [comment]
As you already stated the above bug, I found that executing -RPI.COMMAND when Apple 2 IO RPi was NOT installed in Slot 7,  it immediately returns to the the BASIC prompt. When I executed "RPI a2wifi list", I got a bunch of garbage letters on screen indefinitely.

<img width="1552" alt="Screen Shot 2022-02-06 at 5 08 41 PM" src="https://user-images.githubusercontent.com/10095648/152674358-cef46ba0-9609-4a44-8286-c0521e4e2c57.png">
